---
title: "Portfolio 2"
date: "2025-02-21"
title: "Portfolio Piece 02"
output: html_document
---

### Goal & Product 

The goal of Portfolio Piece 2 is to learn how to create figures for ANOVA results. The product will be a bar chart. 

### Install packages 

```{r install-packages}
#install.packages(c("ggpubr", "broom", "AICcmodavg"))
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(broom)
library(AICcmodavg)
```

```{r load-data}
read.csv("Users/lillymcclendon/Desktop/Portfolio/Study1_Data_for_Analysis_12_09_2024.csv")
```

### Filter data 

```{r filter-data}
library(dplyr)
Study1_Data_filtered <- Study1_Data_for_Analysis_12_09_2024 %>% 
  filter(Valid_1gtr3_C1C2N >= 1, 
         Valid_3gtr1_C1C2N >= 1, 
         Valid_1gtr3_C1C2P >= 1, 
         Valid_3gtr1_C1C2P >= 1, 
         Valid_1gtr3_C1F2N >= 1, 
         Valid_3gtr1_C1F2N >= 1, 
         Valid_1gtr3_C1F2P >= 1,
         Valid_3gtr1_C1F2P >= 1,
         Valid_1gtr3_F1C2N >= 1, 
         Valid_3gtr1_F1C2N >= 1, 
         Valid_1gtr3_F1C2P >= 1, 
         Valid_3gtr1_F1C2P >= 1, 
         Valid_1gtr3_F1F2N >= 1, 
         Valid_3gtr1_F1F2N >= 1, 
         Valid_1gtr3_F1F2P >= 1, 
         Valid_3gtr1_F1F2P >= 1, 
         InvalidTrials >= 4, 
         InvalidTrials <= 28
    ) 
view(Study1_Data_filtered)
```

```{r calculate-overallB1-overallAcc}
library(dplyr)
Study1_Data_filtered <- Study1_Data_filtered %>%
  mutate(Overall_B1 = rowMeans(select(.,Bias_C1C2N, Bias_C1C2P, Bias_C1F2N, Bias_C1F2P, Bias_F1C2N, Bias_F1C2P, Bias_F1F2N, Bias_F1F2P)))
Study1_Data_filtered <- Study1_Data_filtered %>%
  mutate(Overall_Accuracy = rowMeans(select(.,Accuracy_C1C2N, Accuracy_C1C2P, Accuracy_C1F2N, Accuracy_C1F2P, Accuracy_F1C2N, Accuracy_F1C2P, Accuracy_F1F2N, Accuracy_F1F2P)))
print(Study1_Data_filtered)
view(Overall_B1)
```

```{r acc-chance-ttest}
Overall_Accuracy_ttest <- t.test(Study1_Data_filtered$Overall_Accuracy, mu = .50)
print(Overall_Accuracy_ttest)
```

```{r acc-chance-ttest}
Overall_B1_ttest <- t.test(Study1_Data_filtered$Overall_B1, mu = .50)
print(Overall_B1_ttest)
```



